//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCore.Diagnostics.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RDCoreDiagnosticsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RDCoreDiagnosticsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RDCore.Diagnostics.Model.RDCoreDiagnosticsResources", typeof(RDCoreDiagnosticsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les deux opérandes sont des &apos;String&apos;; utiliser l&apos;opérateur de concaténation &apos;&amp;&apos; rendrait l&apos;intention plus explicite ici..
        /// </summary>
        public static string AmbiguousConcatenation_Message {
            get {
                return ResourceManager.GetString("AmbiguousConcatenation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le résultat de cette opération est obtenu en utilisant une arithmétique sur la représentation binaire (en bits) des opérandes. Ceci peut produire des résultats surprenants si on s&apos;attendait ici à une logique conventionnelle. Si l&apos;opération binaire n&apos;est pas intentionnelle, elle pourrait cacher un bug..
        /// </summary>
        public static string BitwiseOperator_Message {
            get {
                return ResourceManager.GetString("BitwiseOperator_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloc de code vide inutile; implémenter un corps, ou en considérer la suppression..
        /// </summary>
        public static string EmptyCodeBlock_Message {
            get {
                return ResourceManager.GetString("EmptyCodeBlock_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloc conditionnel vide; inverser l&apos;expression de la condition en permettrait la simplification..
        /// </summary>
        public static string EmptyIfBlock_Message {
            get {
                return ResourceManager.GetString("EmptyIfBlock_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;énumération d&apos;un tableau est inefficace et serait plus performante en utilisant plutôt une structure `For...Next` et un accès indiciel..
        /// </summary>
        public static string EnumerationOverArray_Message {
            get {
                return ResourceManager.GetString("EnumerationOverArray_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion `DateSerial` implicite; utiliser les fonctions du module `VBA.DateTime` pour effectuer des opérations sur des dates/heures rendrait l&apos;intention plus explicite et simplifierait la lecture en élevant un peu le niveau d&apos;abstraction..
        /// </summary>
        public static string ImplicitDateSerialConversion_Message {
            get {
                return ResourceManager.GetString("ImplicitDateSerialConversion_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coercion `Let` implicite (`{toType.Name}`) de `{fromType.Name}`; invoquer explicitement les membres visés évite les appels implicites &quot;magiques&quot; qui sont difficiles à suivre et à comprendre sans tracer d&apos;obscurs attributs cachés..
        /// </summary>
        public static string ImplicitLetCoercion_message {
            get {
                return ResourceManager.GetString("ImplicitLetCoercion_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion implicite (réduction), d&apos;un type numérique à un autre dont la capacité est moindre - attention, un dépassement arithmétique (overflow) est techniquement possible ici..
        /// </summary>
        public static string ImplicitNarrowingConversion_Message {
            get {
                return ResourceManager.GetString("ImplicitNarrowingConversion_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coercion numérique implicite (`{toType.Name}`) from `{fromType.Name}`; l&apos;utilisation d&apos;une fonction de conversion explicite améliorerait la traçabilité des types impliqués..
        /// </summary>
        public static string ImplicitNumericCoercion_Message {
            get {
                return ResourceManager.GetString("ImplicitNumericCoercion_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coercion `String` implicite depuis `{fromType.Name}`; considérez l&apos;utilisation d&apos;une fonction de conversion explicite (par exemple `CStr`) pour rendre cette opération plus intentionnelle..
        /// </summary>
        public static string ImplicitStringCoercion_Message {
            get {
                return ResourceManager.GetString("ImplicitStringCoercion_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion implicite (élargissement), d&apos;un type numérique à un autre dont la capacité est supérieure; l&apos;utilisation d&apos;une fonction de conversion explicite rendrait l&apos;opération plus intentionnelle..
        /// </summary>
        public static string ImplicitWideningConversion_Message {
            get {
                return ResourceManager.GetString("ImplicitWideningConversion_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appel à liaison tardive (late binding): VBA ne validera pas cet appel au moment de la compilation, ce qui peut produire des erreurs qui seraient évitables en utilisant un type plus spécifique que `Variant` ou `Object`, lorsque c&apos;est possible..
        /// </summary>
        public static string LateBoundMemberAccess_Message {
            get {
                return ResourceManager.GetString("LateBoundMemberAccess_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utiliser la méthode `Err.Raise` pour soulever des erreurs à l&apos;exécution plutôt que l&apos;instruction `Error`, qui comme plusieurs autres instructions existe pour fins de rétro-compatibilité avec des itérations du langage BASIC plus anciennes encore..
        /// </summary>
        public static string PreferErrRaiseOverErrorStatement_Message {
            get {
                return ResourceManager.GetString("PreferErrRaiseOverErrorStatement_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mode de prédiction SLL de l&apos;analyseur a échoué ici; si possible, reformuler cette instruction pourrait améliorer les performances du serveur de langage..
        /// </summary>
        public static string SllFailure_Message {
            get {
                return ResourceManager.GetString("SllFailure_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignation de valeur suspecte: les deux côtés de l&apos;opérateur étant des objets, on dirait vraiment ici que l&apos;intention était plutôt d&apos;effectuer une assignation de référence. Possible qu&apos;il y manque le mot-clé `Set`?.
        /// </summary>
        public static string SuspiciousValueAssignment_Message {
            get {
                return ResourceManager.GetString("SuspiciousValueAssignment_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cette assignation convertit l&apos;objet de droite (RHS) en une interface compatible d&apos;un autre type..
        /// </summary>
        public static string TypeCastConversion_Message {
            get {
                return ResourceManager.GetString("TypeCastConversion_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression constante possiblement non-intentionnelle; cette opération n&apos;affecte pas la valeur..
        /// </summary>
        public static string UnintendedConstantExpression_Message {
            get {
                return ResourceManager.GetString("UnintendedConstantExpression_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appel à liaison tardive non résolu: il semble que cet appel pourrait soulever l&apos;erreur d&apos;exécution 438 (VBR00438)..
        /// </summary>
        public static string UnresolvedLateBoundMemberAccess_Message {
            get {
                return ResourceManager.GetString("UnresolvedLateBoundMemberAccess_Message", resourceCulture);
            }
        }

        
        /// <summary>
        ///   Looks up a localized string for the message of the diagnostic named <c>ImplicitDeclarationsEnabled_Message</c>.
        /// </summary>
        public static string ImplicitDeclarationsEnabled_Message {
            get {
                return ResourceManager.GetString("ImplicitDeclarationsEnabled_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string for the message of the diagnostic named <c>ObsoleteCallStatement_Message</c>.
        /// </summary>
        public static string ObsoleteCallStatement_Message {
            get {
                return ResourceManager.GetString("ObsoleteCallStatement_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the message of the diagnostic named <c>ImplicitNonDefaultArrayBase_Message</c>.
        /// </summary>
        public static string ImplicitNonDefaultArrayBase_Message {
            get {
                return ResourceManager.GetString("ImplicitNonDefaultArrayBase_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the message of the diagnostic named <c>ImplicitTypeDeclarationsEnabled_Message</c>; <c>{0}</c> is the directive.
        /// </summary>
        public static string ImplicitTypeDeclarationsEnabled_Message {
            get {
                return ResourceManager.GetString("ImplicitTypeDeclarationsEnabled_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the message of the diagnostic named <c>ImplicitByRefModifier_Message</c>; <c>{0}</c> is the parameter.
        /// </summary>
        public static string ImplicitByRefModifier_Message {
            get {
                return ResourceManager.GetString("ImplicitByRefModifier_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the message of the diagnostic named <c>ImplicitPublicMember_Message</c>; <c>{0}</c> is the member.
        /// </summary>
        public static string ImplicitPublicMember_Message {
            get {
                return ResourceManager.GetString("ImplicitPublicMember_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the message of the diagnostic named <c>ImplicitVariantDeclaration_Message</c>; <c>{0}</c> is the declared name.
        /// </summary>
        public static string ImplicitVariantDeclaration_Message {
            get {
                return ResourceManager.GetString("ImplicitVariantDeclaration_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the message of the diagnostic named <c>ImplicitVariantReturnType_Message</c>; <c>{0}</c> is the procedure.
        /// </summary>
        public static string ImplicitVariantReturnType_Message {
            get {
                return ResourceManager.GetString("ImplicitVariantReturnType_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the message of the diagnostic named <c>IntegerDataTypeDeclaration_Message</c>.
        /// </summary>
        public static string IntegerDataTypeDeclaration_Message {
            get {
                return ResourceManager.GetString("IntegerDataTypeDeclaration_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the message of the diagnostic named <c>ModuleScopeDimDeclaration_Message</c>.
        /// </summary>
        public static string ModuleScopeDimDeclaration_Message {
            get {
                return ResourceManager.GetString("ModuleScopeDimDeclaration_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the message of the diagnostic named <c>MultilineParameterDeclaration_Message</c>; <c>{0}</c> is the parameter.
        /// </summary>
        public static string MultilineParameterDeclaration_Message {
            get {
                return ResourceManager.GetString("MultilineParameterDeclaration_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the message of the diagnostic named <c>MultipleDeclarations_Message</c>.
        /// </summary>
        public static string MultipleDeclarations_Message {
            get {
                return ResourceManager.GetString("MultipleDeclarations_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the message of the diagnostic named <c>NotAllPathsReturnValue_Message</c>; <c>{0}</c> is the procedure.
        /// </summary>
        public static string NotAllPathsReturnValue_Message {
            get {
                return ResourceManager.GetString("NotAllPathsReturnValue_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the message of the diagnostic named <c>NotAllPathsReturnValue_NeverAssigned_Message</c>; <c>{0}</c> is the procedure.
        /// </summary>
        public static string NotAllPathsReturnValue_NeverAssigned_Message {
            get {
                return ResourceManager.GetString("NotAllPathsReturnValue_NeverAssigned_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the message of the diagnostic named <c>ObsoleteCommentSyntax_Message</c>.
        /// </summary>
        public static string ObsoleteCommentSyntax_Message {
            get {
                return ResourceManager.GetString("ObsoleteCommentSyntax_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the message of the diagnostic named <c>ObsoleteErrorSyntax_Message</c>.
        /// </summary>
        public static string ObsoleteErrorSyntax_Message {
            get {
                return ResourceManager.GetString("ObsoleteErrorSyntax_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the message of the diagnostic named <c>ObsoleteGlobalModifier_Message</c>.
        /// </summary>
        public static string ObsoleteGlobalModifier_Message {
            get {
                return ResourceManager.GetString("ObsoleteGlobalModifier_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the message of the diagnostic named <c>ObsoleteLetStatement_Message</c>.
        /// </summary>
        public static string ObsoleteLetStatement_Message {
            get {
                return ResourceManager.GetString("ObsoleteLetStatement_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the message of the diagnostic named <c>ObsoleteTypeHint_Message</c>; <c>{0}</c> is the name.
        /// </summary>
        public static string ObsoleteTypeHint_Message {
            get {
                return ResourceManager.GetString("ObsoleteTypeHint_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the message of the diagnostic named <c>ObsoleteWhileWend_Message</c>.
        /// </summary>
        public static string ObsoleteWhileWend_Message {
            get {
                return ResourceManager.GetString("ObsoleteWhileWend_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the message of the diagnostic named <c>ObsoleteOnLocalErrorStatement_Message</c>.
        /// </summary>
        public static string ObsoleteOnLocalErrorStatement_Message {
            get {
                return ResourceManager.GetString("ObsoleteOnLocalErrorStatement_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the message of the diagnostic named <c>ImplementationsShouldBePrivate_Interface_Message</c>; <c>{0}</c> is the member.
        /// </summary>
        public static string ImplementationsShouldBePrivate_Interface_Message {
            get {
                return ResourceManager.GetString("ImplementationsShouldBePrivate_Interface_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the message of the diagnostic named <c>ImplementationsShouldBePrivate_EventHandler_Message</c>; <c>{0}</c> is the member.
        /// </summary>
        public static string ImplementationsShouldBePrivate_EventHandler_Message {
            get {
                return ResourceManager.GetString("ImplementationsShouldBePrivate_EventHandler_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the message of the diagnostic named <c>UseMeaningfulIdentifierNames_TooShort_Message</c>; <c>{0}</c> is the name.
        /// </summary>
        public static string UseMeaningfulIdentifierNames_TooShort_Message {
            get {
                return ResourceManager.GetString("UseMeaningfulIdentifierNames_TooShort_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the message of the diagnostic named <c>UseMeaningfulIdentifierNames_EndsWithDigit_Message</c>; <c>{0}</c> is the name.
        /// </summary>
        public static string UseMeaningfulIdentifierNames_EndsWithDigit_Message {
            get {
                return ResourceManager.GetString("UseMeaningfulIdentifierNames_EndsWithDigit_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the message of the diagnostic named <c>UseMeaningfulIdentifierNames_NoVowel_Message</c>; <c>{0}</c> is the name.
        /// </summary>
        public static string UseMeaningfulIdentifierNames_NoVowel_Message {
            get {
                return ResourceManager.GetString("UseMeaningfulIdentifierNames_NoVowel_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the message of the diagnostic named <c>HungarianNotation_Message</c>; <c>{0}</c> is the name.
        /// </summary>
        public static string HungarianNotation_Message {
            get {
                return ResourceManager.GetString("HungarianNotation_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string for the message of the diagnostic named <c>MisleadingByRefParameter_Message</c>; <c>{0}</c> is the parameter.
        /// </summary>
        public static string MisleadingByRefParameter_Message {
            get {
                return ResourceManager.GetString("MisleadingByRefParameter_Message", resourceCulture);
            }
        }
    }
}
