//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCore.SDK {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RDCore.SDK.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language server is already running..
        /// </summary>
        public static string LanguageServerAlreadyRunningException_Message {
            get {
                return ResourceManager.GetString("LanguageServerAlreadyRunningException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verity the state of process ID {$PID}..
        /// </summary>
        public static string LanguageServerAlreadyRunningException_Verbose {
            get {
                return ResourceManager.GetString("LanguageServerAlreadyRunningException_Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server (LSP) could not be located at the configured location..
        /// </summary>
        public static string LanguageServerNotFoundException_Message {
            get {
                return ResourceManager.GetString("LanguageServerNotFoundException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{$LSP_SVR_NAME}&apos; was not found under the configured path: &apos;{$PATH}&apos;..
        /// </summary>
        public static string LanguageServerNotFoundException_Verbose {
            get {
                return ResourceManager.GetString("LanguageServerNotFoundException_Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language client was not initialized..
        /// </summary>
        public static string LanguageServerProtocolSdkException_ClientNotInitialized {
            get {
                return ResourceManager.GetString("LanguageServerProtocolSdkException_ClientNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language server was not initialized..
        /// </summary>
        public static string LanguageServerProtocolSdkException_ServerNotInitialized {
            get {
                return ResourceManager.GetString("LanguageServerProtocolSdkException_ServerNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination data type could only be Null, Variant, or a fixed-sized array..
        /// </summary>
        public static string LetCoercionRuntimeErrorExceptionInvalidUseOfNull_Verbose {
            get {
                return ResourceManager.GetString("LetCoercionRuntimeErrorExceptionInvalidUseOfNull_Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination data type being an object or class type, the data type of the source value cannot be let-coerced, because an object is required for the source value..
        /// </summary>
        public static string LetCoercionRuntimeErrorExceptionObjectRequired {
            get {
                return ResourceManager.GetString("LetCoercionRuntimeErrorExceptionObjectRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source value &apos;Nothing&apos; cannot be let-coerced to an object reference. This error usually denotes a missing &apos;Set&apos; keyword, required for a reference assignment..
        /// </summary>
        public static string LetCoercionRuntimeErrorExceptionObjectVariableNotSet {
            get {
                return ResourceManager.GetString("LetCoercionRuntimeErrorExceptionObjectVariableNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This let-coercion operation is deterministically recursive. See evaluation stack details for more information..
        /// </summary>
        public static string LetCoercionRuntimeErrorExceptionOutOfStackSpace_Verbose {
            get {
                return ResourceManager.GetString("LetCoercionRuntimeErrorExceptionOutOfStackSpace_Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source value is outside the range of the determined let-coercion destination data type and cannot be represented..
        /// </summary>
        public static string LetCoercionRuntimeErrorExceptionOverflow_Verbose {
            get {
                return ResourceManager.GetString("LetCoercionRuntimeErrorExceptionOverflow_Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source value data type could not be let-coerced to the destination declared type during the evaluation of a let-coercion expression..
        /// </summary>
        public static string LetCoercionRuntimeErrorExceptionTypeMismatch_Verbose {
            get {
                return ResourceManager.GetString("LetCoercionRuntimeErrorExceptionTypeMismatch_Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile error (static semantics):.
        /// </summary>
        public static string VBCompileError {
            get {
                return ResourceManager.GetString("VBCompileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is dividing by zero. Consider adding a conditional check to avoid this..
        /// </summary>
        public static string VBDivisionOp_DivisionByZero {
            get {
                return ResourceManager.GetString("VBDivisionOp_DivisionByZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result of a negative exponent value cannot be represented with base 0..
        /// </summary>
        public static string VBExponentOp_InvalidProcedureCallOrArgument_Verbose {
            get {
                return ResourceManager.GetString("VBExponentOp_InvalidProcedureCallOrArgument_Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation results in a division by zero, possibly due to Banker&apos;s Rounding losing enough precision to bring the operand value to integer value 0..
        /// </summary>
        public static string VBIntegerDivisionOp_DivisionByZero {
            get {
                return ResourceManager.GetString("VBIntegerDivisionOp_DivisionByZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relational operator &apos;Is&apos; requires an object in this context..
        /// </summary>
        public static string VBIsOp_ObjectRequired {
            get {
                return ResourceManager.GetString("VBIsOp_ObjectRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run-time error : #.
        /// </summary>
        public static string VBRuntimeError {
            get {
                return ResourceManager.GetString("VBRuntimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation results in a value that the determined effective type cannot legally represent..
        /// </summary>
        public static string VBRuntimeError_ArithmeticOverflow {
            get {
                return ResourceManager.GetString("VBRuntimeError_ArithmeticOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A bound symbol was required to throw a let-coercion type mismatch, but the operand unexpectedly links an unbound &apos;{$SYMBOLTYPE}&apos; symbol..
        /// </summary>
        public static string VBRuntimeInternalError_BoundSymbolExpected_Verbose {
            get {
                return ResourceManager.GetString("VBRuntimeInternalError_BoundSymbolExpected_Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The evaluation of this expression unexpectedly yields a semantically invalid, unrepresentable result..
        /// </summary>
        public static string VBRuntimeInternalError_EvaluateOperatorRuntimeSemanticsNullApplicableResult_Verbose {
            get {
                return ResourceManager.GetString("VBRuntimeInternalError_EvaluateOperatorRuntimeSemanticsNullApplicableResult_Verbo" +
                        "se", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The let-coercion runtime semantic selectors are overlapping and more than a single rule matched..
        /// </summary>
        public static string VBRuntimeInternalError_LetCoercionRuntimeSemanticRulesOverlap {
            get {
                return ResourceManager.GetString("VBRuntimeInternalError_LetCoercionRuntimeSemanticRulesOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The internal let-coercion stack has reached an unexpected desynchronized state. Stack: {$FRAMES}, HashSet: {$HASH}..
        /// </summary>
        public static string VBRuntimeInternalError_LetCoercionStackCorruption {
            get {
                return ResourceManager.GetString("VBRuntimeInternalError_LetCoercionStackCorruption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let-coercion evaluation strategy unexpectedly returned a &apos;NotApplicable&apos; result..
        /// </summary>
        public static string VBRuntimeInternalError_LetCoercionStrategyWasNotApplicable {
            get {
                return ResourceManager.GetString("VBRuntimeInternalError_LetCoercionStrategyWasNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator expression runtime semantics did not receive the expected number of operands for operator &apos;{$OP}&apos;: VBTypedValue[{$LENGTH}]..
        /// </summary>
        public static string VBRuntimeInternalError_WrongNumberOfOperands {
            get {
                return ResourceManager.GetString("VBRuntimeInternalError_WrongNumberOfOperands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No semantics defined an effective type for the specified operator data types ({$OPERANDS})..
        /// </summary>
        public static string VBRuntimeTypeMismatch_OperationEffectiveType_Verbose {
            get {
                return ResourceManager.GetString("VBRuntimeTypeMismatch_OperationEffectiveType_Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error (grammar):.
        /// </summary>
        public static string VBSyntaxError_CustomMessage {
            get {
                return ResourceManager.GetString("VBSyntaxError_CustomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error.
        /// </summary>
        public static string VBSyntaxError_DefaultMessage {
            get {
                return ResourceManager.GetString("VBSyntaxError_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame details:.
        /// </summary>
        public static string Verbose_FrameDetails {
            get {
                return ResourceManager.GetString("Verbose_FrameDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation stack:.
        /// </summary>
        public static string Verbose_LetCoercionStackTrace {
            get {
                return ResourceManager.GetString("Verbose_LetCoercionStackTrace", resourceCulture);
            }
        }
    }
}
