//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCore.SDK; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class ServerOptionsHelpText {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal ServerOptionsHelpText() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RDCore.SDK.ServerOptionsHelpText", typeof(ServerOptionsHelpText).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The maximum number of seconds the server will await a client connection before aborting the initialization process (LSP)..
    /// </summary>
    internal static string ConnectTimeoutSeconds {
        get {
            return ResourceManager.GetString("ConnectTimeoutSeconds", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Configures the healthcheck interval. A client/server process that does not respond in time to health checks may be automatically terminated and the application restarted..
    /// </summary>
    internal static string HealthCheckIntervalSeconds {
        get {
            return ResourceManager.GetString("HealthCheckIntervalSeconds", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The maximum number of instances that can run and connect concurrently..
    /// </summary>
    internal static string MaximumInstances {
        get {
            return ResourceManager.GetString("MaximumInstances", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The name of the named pipe connection, if &apos;TransportLayer&apos; is set to &apos;ServerTransportLayerMode.NamedPipe&apos;..
    /// </summary>
    internal static string PipeName {
        get {
            return ResourceManager.GetString("PipeName", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The port to use for a TCP/socket connection, if the transport is set to &apos;TransportLayerMode.Socket&apos;..
    /// </summary>
    internal static string Port {
        get {
            return ResourceManager.GetString("Port", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The maximum number of seconds the server will wait for an &apos;Exit&apos; notification after receiving a &apos;Shutdown&apos; request..
    /// </summary>
    internal static string ShutdownTimeoutSeconds {
        get {
            return ResourceManager.GetString("ShutdownTimeoutSeconds", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Sets the ServerTransportLayerMode of the client/server application. The same transport layer mode must be supported on both sides of the communication streams..
    /// </summary>
    internal static string TransportLayer {
        get {
            return ResourceManager.GetString("TransportLayer", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Enables verbose extended output, which can then also be controlled by sending a &apos;SetTrace&apos; request from the client. Verbose output may contain symbol names and uri locations..
    /// </summary>
    internal static string Verbose {
        get {
            return ResourceManager.GetString("Verbose", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to An optional workspace or document URI to launch the client/server application with..
    /// </summary>
    internal static string WorkspaceUri {
        get {
            return ResourceManager.GetString("WorkspaceUri", resourceCulture);
        }
    }
}
