//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCore.External {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExternalMessages {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExternalMessages() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RDCore.External.ExternalMessages", typeof(ExternalMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The external host could not answer: {0}.
        /// </summary>
        internal static string HostFailed {
            get {
                return ResourceManager.GetString("HostFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The external host stopped while the call was being made..
        /// </summary>
        internal static string HostStopped {
            get {
                return ResourceManager.GetString("HostStopped", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The external host could not be started..
        /// </summary>
        internal static string HostUnavailable {
            get {
                return ResourceManager.GetString("HostUnavailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The external host that held the object has stopped..
        /// </summary>
        internal static string ObjectHostStopped {
            get {
                return ResourceManager.GetString("ObjectHostStopped", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The object was let go of..
        /// </summary>
        internal static string ObjectReleased {
            get {
                return ResourceManager.GetString("ObjectReleased", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A value of kind &apos;{0}&apos; cannot cross to or from the external host..
        /// </summary>
        internal static string ValueCannotCross {
            get {
                return ResourceManager.GetString("ValueCannotCross", resourceCulture);
            }
        }
    }
}
