<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>logo.ico</ApplicationIcon>
    <Authors>9562-7303 Québec inc.</Authors>
    <Copyright>Copyright © 2026 ${Authors}</Copyright>
    <Product>RDCore</Product>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RDCore.SDK\RDCore.SDK.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="ExternalMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ExternalMessages.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="ExternalMessages.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ExternalMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="RDCore.Tests" />
  </ItemGroup>

</Project>
