<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>9562-7303 Québec inc.</Authors>
    <Copyright>Copyright © 2026 9562-7303 Québec inc.</Copyright>
    <Product>RDCore</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.3.3" />
    <PackageReference Include="NSubstitute" Version="6.2.0" />
    <PackageReference Include="Spectre.Console.Testing" Version="0.57.2" />
    <PackageReference Include="TestableIO.System.IO.Abstractions.TestingHelpers" Version="22.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RDCore.CLI\RDCore.CLI.csproj" />
    <ProjectReference Include="..\RDCore.LanguageServer\RDCore.LanguageServer.csproj" />
    <ProjectReference Include="..\RDCore.Parsing\RDCore.Parsing.csproj" />
    <ProjectReference Include="..\RDCore.Runtime\RDCore.Runtime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

</Project>
