//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCore.LanguageServer.Debugging {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DebuggerMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DebuggerMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RDCore.LanguageServer.Debugging.DebuggerMessages", typeof(DebuggerMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the program cannot go on from there.
        /// </summary>
        internal static string CannotGoOnFromThere {
            get {
                return ResourceManager.GetString("CannotGoOnFromThere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to environment host.
        /// </summary>
        internal static string ComponentEnvironmentHost {
            get {
                return ResourceManager.GetString("ComponentEnvironmentHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the {0} was lost: the program cannot go on..
        /// </summary>
        internal static string ComponentLost {
            get {
                return ResourceManager.GetString("ComponentLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parsing server.
        /// </summary>
        internal static string ComponentParsingServer {
            get {
                return ResourceManager.GetString("ComponentParsingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the expression has no value.
        /// </summary>
        internal static string ExpressionHasNoValue {
            get {
                return ResourceManager.GetString("ExpressionHasNoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an expression is one line.
        /// </summary>
        internal static string ExpressionIsOneLine {
            get {
                return ResourceManager.GetString("ExpressionIsOneLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this file is not part of the workspace.
        /// </summary>
        internal static string FileNotInWorkspace {
            get {
                return ResourceManager.GetString("FileNotInWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (in {1}).
        /// </summary>
        internal static string FrameInHandler {
            get {
                return ResourceManager.GetString("FrameInHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0}.
        /// </summary>
        internal static string GotoTargetLine {
            get {
                return ResourceManager.GetString("GotoTargetLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A launch configuration names the module that has the entry point: &quot;module&quot;..
        /// </summary>
        internal static string LaunchNeedsModule {
            get {
                return ResourceManager.GetString("LaunchNeedsModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no program to start: launch first..
        /// </summary>
        internal static string NoProgramToStart {
            get {
                return ResourceManager.GetString("NoProgramToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no runtime environment component is registered.
        /// </summary>
        internal static string NoRuntimeEnvironment {
            get {
                return ResourceManager.GetString("NoRuntimeEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no statement begins on this line.
        /// </summary>
        internal static string NoStatementOnLine {
            get {
                return ResourceManager.GetString("NoStatementOnLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a module of the workspace.
        /// </summary>
        internal static string NotAModuleOfTheWorkspace {
            get {
                return ResourceManager.GetString("NotAModuleOfTheWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this is not an expression.
        /// </summary>
        internal static string NotAnExpression {
            get {
                return ResourceManager.GetString("NotAnExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this is not one expression.
        /// </summary>
        internal static string NotOneExpression {
            get {
                return ResourceManager.GetString("NotOneExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program was started already..
        /// </summary>
        internal static string ProgramStartedAlready {
            get {
                return ResourceManager.GetString("ProgramStartedAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run-time error.
        /// </summary>
        internal static string RuntimeErrorTitle {
            get {
                return ResourceManager.GetString("RuntimeErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locals.
        /// </summary>
        internal static string ScopeLocals {
            get {
                return ResourceManager.GetString("ScopeLocals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        internal static string ScopeModule {
            get {
                return ResourceManager.GetString("ScopeModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused on breakpoint.
        /// </summary>
        internal static string StopAtBreakpoint {
            get {
                return ResourceManager.GetString("StopAtBreakpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused on Stop statement.
        /// </summary>
        internal static string StopAtStopStatement {
            get {
                return ResourceManager.GetString("StopAtStopStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string StopPaused {
            get {
                return ResourceManager.GetString("StopPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        internal static string StopStep {
            get {
                return ResourceManager.GetString("StopStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string ThreadMain {
            get {
                return ResourceManager.GetString("ThreadMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workspace &apos;{0}&apos; could not be loaded: {1}.
        /// </summary>
        internal static string WorkspaceCouldNotBeLoaded {
            get {
                return ResourceManager.GetString("WorkspaceCouldNotBeLoaded", resourceCulture);
            }
        }
    }
}
