//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCore.SDK.Server {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TraceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TraceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RDCore.SDK.Server.TraceMessages", typeof(TraceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process ID specified in the request exceeds Int32.MaxValue. Skipping health checks; this server instance will not be able to shut down automatically in case of an unexpected problem with the client application..
        /// </summary>
        internal static string InitializeClientProcessIdOutOfRange {
            get {
                return ResourceManager.GetString("InitializeClientProcessIdOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize request did not specify a client process ID. Skipping client process health checks; this server instance will not be able to automatically exit..
        /// </summary>
        internal static string InitializeMissingClientProcessId {
            get {
                return ResourceManager.GetString("InitializeMissingClientProcessId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ ConfigureClient completed..
        /// </summary>
        internal static string LanguageClientConfigurationCompleted {
            get {
                return ResourceManager.GetString("LanguageClientConfigurationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ OnLanguageClientInitializeAsync handler completed..
        /// </summary>
        internal static string LanguageClientInitialize_HandlerCompleted {
            get {
                return ResourceManager.GetString("LanguageClientInitialize_HandlerCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ OnLanguageClientInitializedAsync handler completed..
        /// </summary>
        internal static string LanguageClientInitialized_HandlerCompleted {
            get {
                return ResourceManager.GetString("LanguageClientInitialized_HandlerCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ OnLanguageClientStartedAsync handler completed..
        /// </summary>
        internal static string LanguageClientStarted_HandlerCompleted {
            get {
                return ResourceManager.GetString("LanguageClientStarted_HandlerCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting language client....
        /// </summary>
        internal static string LanguageClientStarting {
            get {
                return ResourceManager.GetString("LanguageClientStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ ConfigureServer completed..
        /// </summary>
        internal static string LanguageServerConfigurationCompleted {
            get {
                return ResourceManager.GetString("LanguageServerConfigurationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Language server is connected and ready..
        /// </summary>
        internal static string LanguageServerConnected {
            get {
                return ResourceManager.GetString("LanguageServerConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ OnLanguageServerInitializeAsync handler completed..
        /// </summary>
        internal static string LanguageServerInitialize_HandlerCompleted {
            get {
                return ResourceManager.GetString("LanguageServerInitialize_HandlerCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ OnLanguageServerInitializedAsync handler completed..
        /// </summary>
        internal static string LanguageServerInitialized_HandlerCompleted {
            get {
                return ResourceManager.GetString("LanguageServerInitialized_HandlerCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ OnLanguageServerStartedAsync handler completed..
        /// </summary>
        internal static string LanguageServerStarted_HandlerCompleted {
            get {
                return ResourceManager.GetString("LanguageServerStarted_HandlerCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting language server....
        /// </summary>
        internal static string LanguageServerStarting {
            get {
                return ResourceManager.GetString("LanguageServerStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ℹ️ LSP language server has terminated. Process will now exit..
        /// </summary>
        internal static string LanguageServerWaitForExitTaskCompleted {
            get {
                return ResourceManager.GetString("LanguageServerWaitForExitTaskCompleted", resourceCulture);
            }
        }
    }
}
