//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCore.CLI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RDCore.CLI.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the listing (source code) of the current program.
        /// </summary>
        public static string Command_List {
            get {
                return ResourceManager.GetString("Command_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown and exit the application..
        /// </summary>
        public static string Command_Quit {
            get {
                return ResourceManager.GetString("Command_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute the current program (or load a new one from a source file).
        /// </summary>
        public static string Command_Run {
            get {
                return ResourceManager.GetString("Command_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the application&apos;s splash screen..
        /// </summary>
        public static string Command_ShowSplash {
            get {
                return ResourceManager.GetString("Command_ShowSplash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright ©{$YEAR} 9562-7303 Québec inc..
        /// </summary>
        public static string CopyrightNotice {
            get {
                return ResourceManager.GetString("CopyrightNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READY..
        /// </summary>
        public static string Prompt_READY {
            get {
                return ResourceManager.GetString("Prompt_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIVAT CUCUMIS.
        /// </summary>
        public static string RDCore_Slogan {
            get {
                return ResourceManager.GetString("RDCore_Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                        kkkkkkkkkkkkkkO                          
        ///                                   kkkkkkkkkkkkkkkkkkkkkkk                      
        ///                                 kkkkkkkkk        kkkkkkkkkkk                   
        ///                               kkkkkkk                kkkkkkkkk                 
        ///                              kkkkkk                     kkkkkkkkkOkO           
        ///                             kkkkkk             kkkkkk     kkkkkkkkkkkkkkkk     
        ///                     [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RDCore_Splash {
            get {
                return ResourceManager.GetString("RDCore_Splash", resourceCulture);
            }
        }
    }
}
