//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDCore.CLI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RDCore.CLI.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied arguments are invalid..
        /// </summary>
        public static string Command_InvalidArgs {
            get {
                return ResourceManager.GetString("Command_InvalidArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the listing (source code) of the current program.
        /// </summary>
        public static string Command_List {
            get {
                return ResourceManager.GetString("Command_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown and exit the application..
        /// </summary>
        public static string Command_Quit {
            get {
                return ResourceManager.GetString("Command_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute the current program (or load a new one from a source file).
        /// </summary>
        public static string Command_Run {
            get {
                return ResourceManager.GetString("Command_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the application&apos;s splash screen..
        /// </summary>
        public static string Command_ShowSplash {
            get {
                return ResourceManager.GetString("Command_ShowSplash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © {$YEAR} {$COMPANY}, all rights reserved..
        /// </summary>
        public static string CopyrightNotice {
            get {
                return ResourceManager.GetString("CopyrightNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A manifest already exists for the specified extension..
        /// </summary>
        public static string DescribeExtension_AlreadyExists {
            get {
                return ResourceManager.GetString("DescribeExtension_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe Extension.
        /// </summary>
        public static string DescribeExtension_Title {
            get {
                return ResourceManager.GetString("DescribeExtension_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reflects an extension executable&apos;s advertised capabilities into an extension manifest.
        /// </summary>
        public static string DescribeExtension_Summary {
            get {
                return ResourceManager.GetString("DescribeExtension_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This command requires the --unsafe-dev-mode switch.
        /// </summary>
        public static string DescribeExtension_DevModeRequired {
            get {
                return ResourceManager.GetString("DescribeExtension_DevModeRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not describe the extension; run this command from within the extension&apos;s folder.
        /// </summary>
        public static string DescribeExtension_Failed {
            get {
                return ResourceManager.GetString("DescribeExtension_Failed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Extension manifest written: {0}.
        /// </summary>
        public static string DescribeExtension_Written {
            get {
                return ResourceManager.GetString("DescribeExtension_Written", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown command.
        /// </summary>
        public static string Command_Unknown {
            get {
                return ResourceManager.GetString("Command_Unknown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Available commands:.
        /// </summary>
        public static string Command_Available {
            get {
                return ResourceManager.GetString("Command_Available", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The specified theme was not found..
        /// </summary>
        public static string Error_ThemeNotFound {
            get {
                return ResourceManager.GetString("Error_ThemeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RDCore™ Extension.
        /// </summary>
        public static string Extension_DefaultDescription {
            get {
                return ResourceManager.GetString("Extension_DefaultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READY..
        /// </summary>
        public static string Prompt_READY {
            get {
                return ResourceManager.GetString("Prompt_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See https://rubberduckvba.ca for additional plugins.
        /// </summary>
        public static string RDCore_SeeWebsiteForPlugins {
            get {
                return ResourceManager.GetString("RDCore_SeeWebsiteForPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {$VIVAT}  ♥  {$CUCUMIS}.
        /// </summary>
        public static string RDCore_Slogan {
            get {
                return ResourceManager.GetString("RDCore_Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                     -+-+--++--                          
        ///                                --+----+----------                      
        ///                              ++-----+-    +--+----+                    
        ///                             -----             +------                  
        ///                            -----         ----   -------------          
        ///                            +---          -----   +-----------+         
        ///                            ----          +--+   ----++ +-----       [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RDCoreSplash_Background {
            get {
                return ResourceManager.GetString("RDCoreSplash_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;======&gt;     &gt;====&gt;            &gt;=&gt;         &gt;=&gt; &gt;=&gt;&gt;=&gt;          &gt;&gt;                 &gt;=&gt;    &gt;=&gt;       &gt;=&gt; 
        ///&gt;=&gt;    &gt;=&gt;   &gt;=&gt;   &gt;=&gt;          &gt;=&gt;       &gt;=&gt;  &gt;&gt;   &gt;=&gt;       &gt;&gt;=&gt;             &gt;=&gt;   &gt;=&gt; &gt;=&gt;       &gt;=&gt; 
        ///&gt;=&gt;    &gt;=&gt;   &gt;=&gt;    &gt;=&gt;          &gt;=&gt;     &gt;=&gt;   &gt;&gt;    &gt;=&gt;     &gt;&gt; &gt;=&gt;           &gt;=&gt;        &gt;=&gt;       &gt;=&gt; 
        ///&gt;&gt; &gt;==&gt;      &gt;=&gt;    &gt;=&gt; &gt;====&gt;    &gt;=&gt;   &gt;=&gt;    &gt;==&gt;&gt;=&gt;      &gt;=&gt;  &gt;=&gt;          &gt;=&gt;        &gt;=&gt;       &gt;=&gt; 
        ///&gt;=&gt;  &gt;=&gt;     &gt;=&gt;    &gt;=&gt;            &gt;=&gt; &gt;=&gt;     &gt;&gt;    &gt;=&gt;   &gt;=====&gt;&gt;=&gt;         &gt;=&gt;        &gt;=&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RDCoreSplash_Foreground {
            get {
                return ResourceManager.GetString("RDCoreSplash_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ™(Trademark registrations pending) • &quot;Rubberduck-VBA&quot; (&quot;RD-VBA&quot;) • &quot;Rubberduck Core&quot; (&quot;RDCore&quot;) • &quot;VIVAT CUCUMIS&quot; | 9562-7303 Québec inc..
        /// </summary>
        public static string TrademarkNotice {
            get {
                return ResourceManager.GetString("TrademarkNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theming is currently disabled..
        /// </summary>
        public static string Warn_ThemingDisabled {
            get {
                return ResourceManager.GetString("Warn_ThemingDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the THEME ON command to enable..
        /// </summary>
        public static string Warn_ThemingDisabled_Verbose {
            get {
                return ResourceManager.GetString("Warn_ThemingDisabled_Verbose", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scaffolds a .rdproj workspace at the given path..
        /// </summary>
        public static string NewWorkspace_Summary {
            get {
                return ResourceManager.GetString("NewWorkspace_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New Workspace.
        /// </summary>
        public static string NewWorkspace_Title {
            get {
                return ResourceManager.GetString("NewWorkspace_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Workspace '{0}' created at {1}.
        /// </summary>
        public static string NewWorkspace_Created {
            get {
                return ResourceManager.GetString("NewWorkspace_Created", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A .rdproj already exists here; pass --force to overwrite..
        /// </summary>
        public static string NewWorkspace_AlreadyExists {
            get {
                return ResourceManager.GetString("NewWorkspace_AlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The path points to an existing file, not a directory..
        /// </summary>
        public static string NewWorkspace_InvalidPath {
            get {
                return ResourceManager.GetString("NewWorkspace_InvalidPath", resourceCulture);
            }
        }
         
        /// <summary>
        ///   Looks up a localized string similar to READY..
        /// </summary>
        public static string Repl_Ready {
            get {
                return ResourceManager.GetString("Repl_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} BYTES RESERVED  {1} AVAILABLE  {2} ALLOCATED  {3} FREE.
        /// </summary>
        public static string Repl_Memory {
            get {
                return ResourceManager.GetString("Repl_Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO RUNTIME SESSION.
        /// </summary>
        public static string Repl_NoSession {
            get {
                return ResourceManager.GetString("Repl_NoSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?SYNTAX ERROR.
        /// </summary>
        public static string Repl_SyntaxError {
            get {
                return ResourceManager.GetString("Repl_SyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?UNDEF'D LINE ERROR.
        /// </summary>
        public static string Repl_UndefinedLine {
            get {
                return ResourceManager.GetString("Repl_UndefinedLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?NOT AVAILABLE ERROR.
        /// </summary>
        public static string Repl_NotAvailable {
            get {
                return ResourceManager.GetString("Repl_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language server does not provide the '{0}' platform capability..
        /// </summary>
        public static string Repl_NotAvailable_Verbose {
            get {
                return ResourceManager.GetString("Repl_NotAvailable_Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BREAK.
        /// </summary>
        public static string Repl_Break {
            get {
                return ResourceManager.GetString("Repl_Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type HELP for a list of commands..
        /// </summary>
        public static string Repl_HelpHint {
            get {
                return ResourceManager.GetString("Repl_HelpHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists the shell commands..
        /// </summary>
        public static string Repl_Help_Summary {
            get {
                return ResourceManager.GetString("Repl_Help_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists the program, or a range of its lines (LIST 100-200)..
        /// </summary>
        public static string Repl_List_Summary {
            get {
                return ResourceManager.GetString("Repl_List_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clears the program..
        /// </summary>
        public static string Repl_New_Summary {
            get {
                return ResourceManager.GetString("Repl_New_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends the session and exits..
        /// </summary>
        public static string Repl_Exit_Summary {
            get {
                return ResourceManager.GetString("Repl_Exit_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs the program..
        /// </summary>
        public static string Repl_Run_Summary {
            get {
                return ResourceManager.GetString("Repl_Run_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzes the program and reports diagnostics..
        /// </summary>
        public static string Repl_Analyze_Summary {
            get {
                return ResourceManager.GetString("Repl_Analyze_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reads the byte at a session memory address..
        /// </summary>
        public static string Repl_Peek_Summary {
            get {
                return ResourceManager.GetString("Repl_Peek_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writes a byte at a session memory address..
        /// </summary>
        public static string Repl_Poke_Summary {
            get {
                return ResourceManager.GetString("Repl_Poke_Summary", resourceCulture);
            }
        }
         
        /// <summary>
        ///   Looks up a localized string similar to ?{0} ERROR.
        /// </summary>
        public static string Repl_RuntimeError {
            get {
                return ResourceManager.GetString("Repl_RuntimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?NOT IMPLEMENTED ERROR.
        /// </summary>
        public static string Repl_NotImplemented {
            get {
                return ResourceManager.GetString("Repl_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?UNDEFINED PROCEDURE ERROR.
        /// </summary>
        public static string Repl_NotFound {
            get {
                return ResourceManager.GetString("Repl_NotFound", resourceCulture);
            }
        }
         
        /// <summary>
        ///   Looks up a localized string similar to NOTHING TO REPORT ({0} PROVIDER(S)).
        /// </summary>
        public static string Repl_Analyze_NoFindings {
            get {
                return ResourceManager.GetString("Repl_Analyze_NoFindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} DIAGNOSTIC(S).
        /// </summary>
        public static string Repl_Analyze_Count {
            get {
                return ResourceManager.GetString("Repl_Analyze_Count", resourceCulture);
            }
        }
         
        /// <summary>
        ///   Looks up a localized string similar to ?ILLEGAL ADDRESS ERROR.
        /// </summary>
        public static string Repl_Memory_NotAllocated {
            get {
                return ResourceManager.GetString("Repl_Memory_NotAllocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?ILLEGAL QUANTITY ERROR.
        /// </summary>
        public static string Repl_Memory_BadArguments {
            get {
                return ResourceManager.GetString("Repl_Memory_BadArguments", resourceCulture);
            }
        }
    }
}
